---
- name: Example Synchronize Module
  hosts: all
  tasks:
  - name: Syncing /home/demo/.config directory ...
    synchronize:
     src: ./sample.txt
     dest: /home/ec2-user/
     delete: yes
     recursive: yes
