---
- hosts: all
  become: True
  become_method: su
  gather_facts: True 
  tasks:
  - name: Configure motd file 1
    copy:
      content: "Container {{inventory_hostname}} is managed by Ansible."
      dest: /etc/motd
  
  - ping:

  - ping:

  - ping:

  - ping:
